// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dembsrrnrngzembpzinw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbWJzcnJucm5nemVtYnB6aW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDU1NzYsImV4cCI6MjA2NjY4MTU3Nn0.6chKmDAvop4XlnnyxBMwvNCir677uKM72weuliiTUJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);